#!/usr/bin/env bash
# remediate.sh — entry script for the nox-remediate composite action.
#
# Modes:
#   plan   — run `nox fix --dry-run` and emit `has-updates` + a plan artifact
#   apply  — run `nox fix` to apply upgrades
#
# Inputs come from environment variables wired in action.yml so we don't
# accidentally surface action inputs into shell quoting bugs.

set -euo pipefail

cmd="${1:-}"
if [[ -z "$cmd" ]]; then
  echo "remediate.sh: missing subcommand (plan|apply)" >&2
  exit 2
fi

OUTPUT_DIR="${INPUT_OUTPUT:-nox-out}"
MANIFEST_ROOT="${INPUT_MANIFEST_ROOT:-.}"
INCLUDE_MAJOR="${INPUT_INCLUDE_MAJOR:-false}"
UPGRADE_ACTIONS="${INPUT_UPGRADE_ACTIONS:-false}"
FINDINGS_PATH="${OUTPUT_DIR}/findings.json"
PLAN_PATH="${OUTPUT_DIR}/remediation-plan.txt"
PR_BODY_PATH="${OUTPUT_DIR}/pr-body.md"

mkdir -p "$OUTPUT_DIR"

if [[ ! -f "$FINDINGS_PATH" ]]; then
  echo "remediate.sh: $FINDINGS_PATH not found — did the install/scan step run?" >&2
  exit 2
fi

extra_args=()
if [[ "$INCLUDE_MAJOR" == "true" ]]; then
  extra_args+=("--include-major")
fi
if [[ "$UPGRADE_ACTIONS" == "true" ]]; then
  # Adds the workflow-pin pass alongside the package pass, so GitHub Action
  # versions are upgraded and SHA-pinned in the same PR.
  extra_args+=("--actions")
fi

case "$cmd" in
  plan)
    set +e
    nox fix --input "$FINDINGS_PATH" --root "$MANIFEST_ROOT" --dry-run "${extra_args[@]}" \
      | tee "$PLAN_PATH"
    plan_status=${PIPESTATUS[0]}
    set -e
    if [[ $plan_status -ne 0 ]]; then
      echo "remediate.sh: nox fix --dry-run exited $plan_status" >&2
      exit "$plan_status"
    fi

    # Detect work by the presence of planned changes, not by the absence of the
    # package pass's "nothing to do" line.
    #
    # `nox fix` runs two passes and each reports independently, so with
    # --actions the output routinely reads:
    #
    #     nox fix: no eligible upgrades found.       <- packages
    #     plan: golangci/golangci-lint-action ...    <- actions
    #
    # Matching the first line alone therefore concluded "no updates" while real
    # action upgrades sat directly beneath it, and the apply and PR steps were
    # skipped. Both passes announce actual work with a `plan:` line, so that is
    # the signal.
    if grep -qE '^plan: ' "$PLAN_PATH"; then
      has_updates="true"
    else
      has_updates="false"
    fi

    {
      echo "## Summary"
      echo ""
      echo "Generated by [nox-remediate](https://github.com/nox-hq/nox-remediate-action)."
      echo ""
      echo "## Plan"
      echo ""
      echo '```text'
      cat "$PLAN_PATH"
      echo '```'
      echo ""
      echo "## Verification"
      echo ""
      echo "Run by the workflow's \`verify-cmd\` step (if configured)."
    } > "$PR_BODY_PATH"

    {
      echo "has-updates=$has_updates"
      echo "plan-file=$PLAN_PATH"
    } >> "${GITHUB_OUTPUT:-/dev/stdout}"
    ;;

  apply)
    nox fix --input "$FINDINGS_PATH" --root "$MANIFEST_ROOT" "${extra_args[@]}"
    ;;

  *)
    echo "remediate.sh: unknown subcommand: $cmd" >&2
    exit 2
    ;;
esac
